### ISSUE TITLE
Action can't find template in .github directory

### ISSUE THREAD

**Issue by rkleinman-hpe** [chuhlomin/render-template#1]
Trying to use this action, but it can't seem to find my template file. Here is my action:

```yaml
      - name: Render template
        id: template
        uses: chuhlomin/render-template@v1.2
        with:
          template: .github/build-image-comment-template.md
          vars: |
            fullImageWithShaTag: ${{ needs.build-docker-image.outputs.fullImageWithShaTag }}
            imageWithShaTag: ${{ needs.build-docker-image.outputs.imageWithShaTag }}
```

Here is the contents of my repo:

```bash

$ tree -a .github
.github
├── CODEOWNERS
├── build-image-comment-template.md
├── dependabot.yml
├── pull_request_template.md
└── workflows
    ├── build-image.yml
    └── charts-lint-test-scan.yml

1 directory, 6 files
```

Here is the output of my action job run:

```
Run chuhlomin/render-template@v1.2
  with:
    template: .github/build-image-comment-template.md
    vars: fullImageWithShaTag: artifactory.algol60.net/csm-docker/unstable/cray-product-catalog-update:sha-6d034b4a01d0f44e6f5429cf64e9e838112ec337
  imageWithShaTag: cray-product-catalog-update:sha-6d034b4a01d0f44e6f5429cf64e9e838112ec337
  
/usr/bin/docker run --name chuhlominrendertemplatev12_faa8fc --label 6a6825 --workdir /github/workspace --rm -e INPUT_TEMPLATE -e INPUT_VARS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/cray-product-catalog/cray-product-catalog":"/github/workspace" chuhlomin/render-template:v1.2
Error: template file not found (".github/build-image-comment-template.md")
```
