### ISSUE TITLE
Multiline strings are being stripped of newlines

### ISSUE THREAD

**Issue by andyatterton** [chuhlomin/render-template#16]
I am supplying a multiline string of features and notes to a template using the syntax as stated in the actions documentation

```
{name}<<{delimiter}
{value}
{delimiter}
```
[https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings](url)

It appears to go into the action just fine

![image](https://github.com/chuhlomin/render-template/assets/57716459/d0e947a5-a76c-4454-8ada-751294edf716)

But once it renders the new lines have been removed (note that the notes have an extra line between each which is stripped)

![image](https://github.com/chuhlomin/render-template/assets/57716459/438a899a-61f7-4b5f-873d-9a544bd1462c)

Code from the action just in case I'm not supplying the vars in the intended way

```echo "${FEATURE_COMMITS}"
          {
            echo 'pr_features<<EOF'
            echo "${FEATURE_COMMITS}"
            echo EOF
          } >> $GITHUB_OUTPUT
```
```
name: Render Template
        id: template
        uses: chuhlomin/render-template@v1
        with:
          template: .github/pull_request_template.md
          vars: |
            pr_date: ${{ steps.get_current_date.outputs.current_date }}
            pr_feature: "${{ steps.pr_features.outputs.pr_features }}"
            pr_notes: "${{ steps.pr_notes.outputs.pr_notes }}"
```
