### ISSUE TITLE
What does "Container action is only supported on Linux" mean?

### ISSUE THREAD

**Issue by dnedrow** [chuhlomin/render-template#18]
Given the error "Container action is only supported on Linux", I'm guessing this action won't work on a macOS runner?

Below is what I'm attempting. Should this work on a macOS runner? I'm not sure if I've just configured something wrong, or was expecting too much from the action.

```markdown
#Test Template

Use the link(s) below to download artifacts created by this build.
  
* {{ .foourl | mdlink "Foo Artifact" }}
* {{ .barurl | mdlink "Bar Artifact" }}
```

```yaml
      - name: Render template
        id: artifact-template
        uses: chuhlomin/render-template@v1.4
        with:
          template: .github/ACTION_TEMPLATES/artifact-download-template.md
          vars: |
            foourl: ${{ steps.artifact-upload-step-foo.outputs.artifact-url }}
            barurl: ${{ steps.artifact-upload-step-bar.outputs.artifact-url }}
```
