### ISSUE TITLE
Generate a new file from the processed file

### ISSUE THREAD

**Issue by cmoulliard** [chuhlomin/render-template#25]
## Feature request

Could it be possible to generate a new file from the processed file as by this action do ?

```
      - name: Render template
        id: render_template
        uses: chuhlomin/render-template@v1
        env:
         VM_IMAGES_NAMESPACE: TOTO
        with:
          template: templates/quarkus-dev-virtualmachine.tmpl
          target: quarkus-dev-virtualmachine.yaml
          vars: |
            vmImagesNamespace: ${{ env.VM_IMAGES_NAMESPACE }}
```
