### ISSUE TITLE
Multiline template vars

### ISSUE THREAD

**Issue by stevelacey** [chuhlomin/render-template#3]
> env: parse error on field "Vars" of type "main.vars": unable to parse Vars: yaml: mapping values are not allowed in this context

Are multiline vars supported? Could they be?

My use case is piping diffs into the template, so I'm trying stuff like this but running into yaml errors:

```yaml
vars: |
  pip_diff: |
    ${{ env.PIP_DIFF }}
  npm_diff: |
    ${{ env.NPM_DIFF }}
```

I was originally trying to do it via `set-output` with the [preserve newlines fix](https://github.community/t/set-output-truncates-multiline-strings/16852/3), now I'm trying env, but I figure this is going to be hard to make work via yaml, unless I want to get into the business of swapping out `\n` for `(2? spaces)\n`.

**Comment by chuhlomin** [comment]
Hey, multiline vars are supported, but you have to follow YAML spec and indent each line accordingly.
Unfortunately, GitHub doesn't provide any function to indent each line for that use case.
As an idea, you can wrap vars with quotes, at cost of losing newlines:

```yaml
vars: |
  pip_diff: "${{ env.PIP_DIFF }}"
  npm_diff: "${{ env.NPM_DIFF }}"
```

I don't see any way it can be solved at the app level... unless you put these vars values into a files and then app will read these files somehow, like:

```yaml
vars: |
  some_over_key: val
vars_files:
  pip_diff: pip.diff
  npm_diff: npm.diff
```

Let me know what you think

**Comment by stevelacey** [comment]
I didn't end up using this action after all, but my gripes largely seemed to stem from the way vars are accepted, if it was an object of vars instead of a string there'd be no indentation issue, appreciate there might be platform limitations in that.

In the end I went with something along the lines of:

```yaml
- id: package-lock-diff
  run: |
    diff=$(/path/to/make/diff/thing)
    diff="${diff//'%'/'%25'}"
    diff="${diff//$'\n'/'%0A'}"
    diff="${diff//$'\r'/'%0D'}"
    echo ::set-output name=diff::$diff

- uses: peter-evans/create-pull-request@v3
  with:
    title: Package updates [frontend]
    body: |
      ```
      ${{ steps.package-lock-diff.outputs.diff }}
      ```
    commit-message: |
      Package updates [frontend]

      ${{ steps.package-lock-diff.outputs.diff }}
```
