### ISSUE TITLE
How to delimit with newline in template?

### ISSUE THREAD

**Issue by kchaung-lilly** [chuhlomin/render-template#32]
Hi, I was wondering if you had any advice on incorporating newline characters in the template?

In this example, I have a string variable called `added_files` which looks like: `a.txt b.txt c.txt`

I would like to use a template to render a comment that looks like
```
The files are:
a.txt
b.txt
c.txt
```

I have tried:
1. replacing the spaces with literal newlines in `added_files` input vars, gives me this error
```
Error: env: parse error on field "Vars" of type "main.vars": unable to parse Vars: yaml: line 3: could not find expected ':'
```
2. A template that looks like:
```
The added files are:
{{ .added_files | replace " " "\n" }}
```
Gives me this error:
```
Error: failed to render template: template: .github/templates/comment.md:5: function "replace" not defined
```

Would you happen to have any advice on this? Thank you!

**Comment by chuhlomin** [comment]
Hi, there are a few ways to do that.

First, you could use the `split` function (which calls `strings.Split` under the hood, so that you'll get a slice (list/array) in the template, and then you could use it with `range` to iterate over.

```yaml
      - name: Test action
        with:
          template: ./testdata/list_of_files.md
          vars: |
            added_files: a.txt b.txt c.txt
```

Template:
```
The files are:
{{- $list := .added_files | split " " }}
{{- range $list }}
- {{ . }}
{{- end }}
```

Output:
```
The files are:
- a.txt
- b.txt
- c.txt
```

Alternatively, you could pass the actual list to the template. It is a bit more tricky, because when passing YAML inside another YAML you have to remember to keep the indentation with every new line. This is likely why you got the `could not find expected ':'` error. Action call will look like:
```yaml
      - name: Test action
        with:
          template: ./testdata/list_of_files.md
          vars: |
            added_files:
              - a.txt
              - b.txt
              - c.txt
```
Template:
```
The files are:
{{- range .added_files }}
- {{ . }}
{{- end }}
```
Output is the same.

Here is the GHA run where I tested it: https://github.com/chuhlomin/render-template/actions/runs/13534452386/job/37823414095 ([diff](https://github.com/chuhlomin/render-template/compare/chuhlomin:5b41186...chuhlomin:b6688cb))

Also, if you use that template later somewhere that consumes Markdown, I recommend taking a look at `mdlink` template function, to turn these filenames into links. It would look something like this
```
{{- range .added_files }}
- {{ (print "https://github.com/owner/repo/blob/branch/" .) | mdlink . }}
{{- end }}
```

Please let me know if still would like to have `replace` template function.
